### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by lrausch** [Open-Power-System-Data/renewable_power_plants#13]
I have some suggestions:

Wrong order of dso. dso_id and eeg_id in more than 25000 records from TransnetBW
Try
select * from database
where dso like 'E1%' 

Technology for hydro is not always run-of-river. At least 1 plant is hydro-pumped-storage with natural inflow (eeg_id = E40000095595202). 
Biomass power plants with 10-20MW have solid fuel.

Lothar

**Comment by krischan1** [comment]
Thanks for the suggestions. We have been aware of the issue within the TransnetBW data and will solve that issue within the next update.

Thanks and BR

Kristian
